Add the option to use relative paths
adrienblanchard/include-shader pull request #1
Opened 2023-03-05 00:03 UTC by DouglasDwyer

Most of the include macros in the standard library, such as `include_str` and `include_bytes`, accept paths relative to the current directory rather than the workspace root. This change adds a feature flag, `relative-path`, which causes this crate to mirror the standard library's functionality. This makes it easier to migrate from using `include_str` to `include_shader`.

2023-03-11 23:02 UTC, adrienblanchard requested changes
Thanks a lot @DouglasDwyer.

I agree and like the idea of mirroring the behaviors of the std macros like `include_str`. 

It's unfortunate that the `proc_macro_span` API has been stagnant for a while now and is still experimental.

I guess we have no choice but to gate it behind a feature flag for now for backward compatibility in hope that in the future we can introduce this change on both stable and nightly toolchains as a major release with breaking change.

I have created a new branch (0.2.0) for the next upcoming release, which will contain this enhancement along with other documentation and code improvements that I am currently working on. 

In order for this PR to move forward, could we please:

- Change the PR target branch to the upcoming release branch (0.2.0)
- Review comments and requested changes

2023-03-11 23:02 UTC, adrienblanchard commented on Cargo.toml
> +relative-path = [ "nightly" ]
Could we please remove the enabling of the nightly feature? This will make relative-path standalone and avoid any future side effects.

```suggestion
relative-path = []
```

2023-03-11 23:02 UTC, adrienblanchard commented on src/lib.rs
> +    }
In order to reduce code complexity and feature flag checks, could we please refacto this part?

```suggestion
    #[allow(unused_assignments)]
    let mut call_parent_dir_path = None;
    
    #[cfg(feature = "relative-path")] {
        let mut path = proc_macro::Span::call_site().source_file().path();
        path.pop();
        call_parent_dir_path = Some(path);
    }

    let root_path = resolve_path(&arg, call_parent_dir_path);
```

2023-03-11 23:02 UTC, adrienblanchard commented on src/lib.rs
> +        }
In order to reduce code complexity and feature flag checks, could we please refacto this part?

```suggestion
        #[allow(unused_assignments)]
        let mut include_parent_dir_path = None;
        
        #[cfg(feature = "relative-path")] {
            let mut path = source_path.to_path_buf();
            path.pop();
            include_parent_dir_path = Some(path);
        }
        
        let include_path = resolve_path(captures.name("file").unwrap().as_str(), include_parent_dir_path);
```

2023-03-11 23:02 UTC, adrienblanchard commented on src/lib.rs
> +    }.unwrap_or_else(|e| {
Could you please explain why are we doing `skip(1)` on the path?

Please correct me if I am wrong, but I believe this could be simplified to this:

```suggestion
fn resolve_path(path: &str, parent_dir_path: Option<PathBuf>) -> PathBuf {
    let mut path = PathBuf::from(path);

    if let Some(p) = parent_dir_path {
        if !path.is_absolute() {
            path = p.join(path);
        }
    }

    canonicalize(&path).unwrap_or_else(|e| {
        panic!(
            "An error occured while trying to resolve path: {:?}. Error: {}",
            path, e
        )
    })
}
```

2023-03-11 23:02 UTC, adrienblanchard commented on src/lib.rs
> +//! This mirrors the behavior of [`include_str`](https://doc.rust-lang.org/std/macro.include_str.html).
Could we please remove the comment line referring to the `include_str` macro doc?

```suggestion
```

2023-03-13 23:19 UTC, DouglasDwyer commented on src/lib.rs
> +    }.unwrap_or_else(|e| {
There are two cases here:
- The path is relative, and searching should occur based upon the current document.
- The path is "absolute" - which should mean that it is absolute to the crate root. So a path like `/src/temp.glsl` should globally refer to `{CRATE_ROOT}/src/temp.glsl`, no matter where the current file is.

Unfortunately, `path.is_absolute()` does not actually work for the second case. `path.is_absolute` only returns true on Windows for paths that begin with a drive letter or `\\?\`. So the current changes are the (albeit ugly) workaround that I came up with. `p.has_root()` _does_ return true for any path that starts with `/`, so we use that to check whether the path should be crate-root relative, and if it is, then we use `skip(1)` to strip the leading `/`. If `skip(1)` is not used, then `/src/temp.glsl` is interpreted on Windows as `C:\src\temp.glsl`.

I'm happy to refactor the `skip(1)` into a separate function for increased clarity. But I believe that such a workaround is necessary in this case.

2023-03-17 21:06 UTC, adrienblanchard commented on src/lib.rs
> +    }.unwrap_or_else(|e| {
Thank you for the detailed explanation.

Now wondering if we are trying to handle a case that is not required. Please correct me if I am wrong, but from some quick testing on my Windows machine, it seems like:

- `std::include_str` does not support the leading `/`, it throws an error instead. A relative path is required

- `std::fs::canonicalize` does not support the leading `/`, it throws an error instead. Only relative paths starting with a leading dot slash `./` or a path with no leading `/` are supported, and are resolved from the workspace root directory

Furthermore, the library current version `0.1.1` is using `std::fs::canonicalize` directly to resolve the paths, which would mean that the leading `/` is currently not supported.

Rust source code seems to use `is_absolute` for `std::include_str` to resolve the paths: https://doc.rust-lang.org/nightly/nightly-rustc/src/rustc_expand/base.rs.html#1184-1214

Your thoughts? Any comments or suggestions on this would be greatly appreciated.

2023-03-17 22:30 UTC, DouglasDwyer commented on src/lib.rs
> +    }.unwrap_or_else(|e| {
Interesting - thanks for looking through the standard library implementation. If `include_str` and the like require a relative path, then I believe that we should do the same. I'll go ahead and refactor my code to mirror the linked Rust source :)

2023-03-20 21:33 UTC, adrienblanchard approved these changes

2023-03-20 21:44 UTC, merged